export default {
  // V2-specific picklist values for testing
  registries: [
    'V2 Test Registry A',
    'V2 Test Registry B',
    'V2 Test Registry C',
  ],
  projectSector: [
    'V2 Agriculture',
    'V2 Forestry',
    'V2 Energy',
    'V2 Manufacturing',
    'V2 Transportation',
  ],
  projectType: [
    'V2 Afforestation',
    'V2 Reforestation',
    'V2 Forest Management',
    'V2 Soil Carbon',
    'V2 Renewable Energy',
    'V2 Energy Efficiency',
    'V2 Waste Management',
  ],
  methodologyType: [
    'V2 Forestry',
    'V2 Agriculture',
    'V2 Energy',
    'V2 Waste',
    'V2 Transport',
  ],
  coveredByNDC: ['V2 Inside NDC', 'V2 Outside NDC', 'V2 Unknown'],
  projectStatusValues: [
    'V2 Listed',
    'V2 Registered',
    'V2 Completed',
    'V2 Transitioned',
    'V2 Withdrawn',
  ],
  unitMetric: ['V2 tCO2e', 'V2 tCO2', 'V2 tCH4'],
  validationType: [
    'V2 Third Party',
    'V2 Self Assessment',
    'V2 Peer Review',
  ],
  validationBody: [
    'V2 Test Validator A',
    'V2 Test Validator B',
    'V2 Test Validator C',
  ],
  verificationBody: [
    'V2 Test Verifier A',
    'V2 Test Verifier B',
    'V2 Test Verifier C',
  ],
  unitType: [
    'V2 Reduction - Nature',
    'V2 Reduction - Technical',
    'V2 Removal - Nature',
    'V2 Removal - Technical',
  ],
  unitStatus: [
    'V2 Held',
    'V2 Retired',
    'V2 Cancelled',
    'V2 Exported',
    'V2 Pending Export',
  ],
  countries: [
    'V2 Test Country A',
    'V2 Test Country B',
    'V2 Test Country C',
    'V2 Test Country D',
    'V2 Test Country E',
  ],
  stakeholderType: [
    'V2 Project Developer',
    'V2 Investor',
    'V2 Buyer',
    'V2 Verifier',
    'V2 Validator',
  ],
  labelType: [
    'V2 Endorsement',
    'V2 Certification',
    'V2 Approval',
    'V2 Authorization',
  ],
  ratingType: [
    'V2 BeZero',
    'V2 CDP',
    'V2 CCQI',
    'V2 MAAP',
    'V2 Sylvera',
  ],
  coBenefits: [
    'V2 SDG 1 - No poverty',
    'V2 SDG 2 - Zero hunger',
    'V2 SDG 3 - Good health',
    'V2 SDG 4 - Quality education',
    'V2 SDG 5 - Gender equality',
    'V2 SDG 6 - Clean water',
    'V2 SDG 7 - Clean energy',
    'V2 SDG 8 - Economic growth',
    'V2 SDG 9 - Infrastructure',
    'V2 SDG 10 - Reduced inequalities',
    'V2 SDG 11 - Sustainable cities',
    'V2 SDG 12 - Responsible consumption',
    'V2 SDG 13 - Climate action',
    'V2 SDG 14 - Life below water',
    'V2 SDG 15 - Life on land',
    'V2 SDG 16 - Peace and justice',
    'V2 SDG 17 - Partnerships',
  ],
  activityType: [
    'V2 Activity Type A',
    'V2 Activity Type B',
    'V2 Activity Type C',
  ],
  authorizationPurpose: [
    'V2 Purpose A',
    'V2 Purpose B',
    'V2 Purpose C',
  ],
  actionType: [
    'V2 Action Type A',
    'V2 Action Type B',
    'V2 Action Type C',
  ],
  mitigationType: [
    'V2 Mitigation Type A',
    'V2 Mitigation Type B',
    'V2 Mitigation Type C',
  ],
};
