export default {
  // V2 default picklist values - used as fallback when governance node is unavailable
  // and as the picklist for simulator/development mode

  projectSector: [
    'Afforestation and reforestation',
    'Agriculture',
    'Any combination of the above',
    'Carbon capture and storage',
    'Chemical industries',
    'Construction',
    'Energy demand',
    'Energy distribution',
    'Energy industries (renewable-/ non renewable sources)',
    'Fugitive emissions from fuel (solid, oil and gas)',
    'Fugitive emissions from the production and consumption of halocarbons and sulfur hexafluoride',
    'Livestock and manure management',
    'Manufacturing industries',
    'Metal production',
    'Mining/mineral production',
    'Others',
    'Solvent use',
    'Transport',
    'Urban Development',
    'Waste handling and disposal',
  ],

  aefT2AuthorizationsSector: [
    'Afforestation and reforestation',
    'Agriculture',
    'Agriculture forestry and other land use (AFOLU)',
    'Any combination of the above',
    'Carbon capture and storage',
    'Chemical industries',
    'Construction',
    'Energy demand',
    'Energy distribution',
    'Energy industries (renewable-/ non renewable sources)',
    'Fugitive emissions from fuel (solid, oil and gas)',
    'Fugitive emissions from the production and consumption of halocarbons and sulfur hexafluoride',
    'Livestock and manure management',
    'Manufacturing industries',
    'Metal production',
    'Mining/mineral production',
    'Others',
    'Solvent use',
    'Transport',
    'Urban Development',
    'Waste handling and disposal',
  ],

  projectType: [
    'Afforestation',
    'Agriculture',
    'Agriculture, forestry and other land use (AFOLU)',
    'Any combination of the above',
    'Biogas',
    'Biomass Energy',
    'CO2 usage',
    'Cement',
    'Coal bed/mine methane',
    'Energy Efficiency Industry',
    'Energy Efficiency households',
    'Energy Efficiency own generation',
    'Energy Efficiency service',
    'Energy Efficiency supply side',
    'Energy distribution',
    'Fugitive',
    'Geothermal',
    'Hydro',
    'Landfill gas',
    'Methane avoidance',
    'N2O',
    'PFCs and SF6',
    'Reforestation',
    'Solar',
    'Tidal',
    'Transport',
    'Waste',
    'Wind',
  ],

  aefT2AuthorizationsActivityType: [
    'Afforestation',
    'Agriculture',
    'Any combination of the above',
    'Biogas',
    'Biomass Energy',
    'CO2 usage',
    'Cement',
    'Coal bed/mine methane',
    'Energy Efficiency Industry',
    'Energy Efficiency households',
    'Energy Efficiency own generation',
    'Energy Efficiency service',
    'Energy Efficiency supply side',
    'Energy distribution',
    'Fossil fuel switch',
    'Fugitive',
    'Geothermal',
    'Hydro',
    'Landfill gas',
    'Methane avoidance',
    'N2O',
    'PFCs and SF6',
    'Reforestation',
    'Solar',
    'Tidal',
    'Transport',
    'Waste',
    'Wind',
  ],

  projectStatus: [
    'Certified',
    'Completed',
    'Inactive',
    'Listed',
    'Registered',
    'Rejected',
    'Validated',
    'Verified',
    'Withdrawn',
  ],

  projectUnitMetric: [
    'gCO2eq/kWh',
    'kt (Kiloton)',
    'tCO2e',
  ],

  unitMetric: [
    'gCO2eq/kWh',
    'kt (Kiloton)',
    'tCO2e',
  ],

  validationBody: [
    '350 Solutions',
    '4K Earth Science Private Limited',
    'AENOR International S.A.U.',
    'Agri-Waste Technology Inc.',
    'Ampere For Renewable Energy',
    'Asociación de Normalización y Certificación A.C.',
    'Aster Global Environmental Solutions Inc.',
    'Bureau Veritas India Private Limited',
    'CGN Certification',
    'Carbon Check (India) Private Limited',
    'China Building Material Test & Certification Group Co. Limited',
    'China Certification Center Inc.',
    'China Classification Society Certification Co. Limited',
    'China Environmental United Certification Center Co. Limited',
    'China Quality Certification Center',
    'China Testing & Certification International Group Co. Limited',
    'Colombian Institute for Technical Standards and Certification',
    'Control Union Certifications Germany GmbH',
    'Deloitte Tohmatsu Sustainability Co. Limited',
    'Det Norske Veritas (U.S.A.) Inc.',
    'Deutsche Certification Body',
    'EPIC Sustainability Services Private Limited',
    'ERM Certification and Verification Services Limited',
    'Earthood Services Private Limited',
    'EnergyLink Services',
    'Enviance Services Private',
    'Enviro-Accès Inc.',
    'Environmental Services Inc.',
    'First Environment Inc.',
    'GHD Limited',
    'GHD Services Inc.',
    'Japan Quality Assurance Organisation',
    'KBS Certification Services Private Limited',
    'KPMG International Limited',
    'Korea Energy Agency',
    'Korea Testing & Research Institute',
    'Korean Foundation for Quality',
    'Korean Standards Association',
    'LGAI Technological Center S.A.',
    'PT Superintending Company of Indonesia (PT SUCOFINDO) - SBU Sertifikasi da Eco Framework (Sucofindo International Certification Services)',
    'QSI Belgelendirme Muayene Ve Test Hizmetleri Limited Şti.',
    'RINA Services S.p.A',
    'Rainforest Alliance Inc.',
    'Re Carbon Limited',
    'Ruby Canyon Environmental Inc',
    'S&A Carbon LLC',
    'SCS Global Services',
    'SQS (The Swiss Association for Quality and Management Systems)',
    'Shenzhen CTI International Certification Co. Limited',
    'The Earth Lab',
    'TÜV Nord Cert GmbH',
    'TÜV Rheinland (China) Limited',
    'TÜV SÜD America Inc. - Ruby Canyon',
    'TÜV SÜD South Asia Private Limited',
    'VKU Certification Private Limited',
    'Verico SCE',
    'Verifit',
    'Versa Expertos en Certificación',
  ],

  verificationBody: [
    '350 Solutions',
    '4K Earth Science Private Limited',
    'AENOR International S.A.U.',
    'Agri-Waste Technology Inc.',
    'Ampere For Renewable Energy',
    'Asociación de Normalización y Certificación A.C.',
    'Aster Global Environmental Solutions Inc.',
    'Bureau Veritas India Private Limited',
    'CGN Certification',
    'Carbon Check (India) Private Limited',
    'China Building Material Test & Certification Group Co. Limited',
    'China Certification Center Inc.',
    'China Classification Society Certification Co. Limited',
    'China Environmental United Certification Center Co. Limited',
    'China Quality Certification Center',
    'China Testing & Certification International Group Co. Limited',
    'Colombian Institute for Technical Standards and Certification',
    'Control Union Certifications Germany GmbH',
    'Deloitte Tohmatsu Sustainability Co. Limited',
    'Det Norske Veritas (U.S.A.) Inc.',
    'Deutsche Certification Body',
    'EPIC Sustainability Services Private Limited',
    'ERM Certification and Verification Services Limited',
    'Earthood Services Private Limited',
    'EnergyLink Services',
    'Enviance Services Private',
    'Enviro-Accès Inc.',
    'Environmental Services Inc.',
    'First Environment Inc.',
    'GHD Limited',
    'GHD Services Inc.',
    'Japan Quality Assurance Organisation',
    'KBS Certification Services Private Limited',
    'KPMG International Limited',
    'Korea Energy Agency',
    'Korea Testing & Research Institute',
    'Korean Foundation for Quality',
    'Korean Standards Association',
    'LGAI Technological Center S.A.',
    'PT Superintending Company of Indonesia (PT SUCOFINDO) - SBU Sertifikasi da Eco Framework (Sucofindo International Certification Services)',
    'QSI Belgelendirme Muayene Ve Test Hizmetleri Limited Şti.',
    'RINA Services S.p.A',
    'Rainforest Alliance Inc.',
    'Re Carbon Limited',
    'Ruby Canyon Environmental Inc',
    'S&A Carbon LLC',
    'SCS Global Services',
    'SQS (The Swiss Association for Quality and Management Systems)',
    'Shenzhen CTI International Certification Co. Limited',
    'The Earth Lab',
    'TÜV Nord Cert GmbH',
    'TÜV Rheinland (China) Limited',
    'TÜV SÜD America Inc. - Ruby Canyon',
    'TÜV SÜD South Asia Private Limited',
    'VKU Certification Private Limited',
    'Verico SCE',
    'Verifit',
    'Versa Expertos en Certificación',
  ],

  methodologyType: [
    'Avoidance - nature',
    'Avoidance - technical',
    'Not Determined',
    'Reduction - nature',
    'Reduction - technical',
    'Removal - nature',
    'Removal - technical',
  ],

  validationType: [
    'Validation of Post Registration Change',
    'Validation of Project Design Document',
    'Validation of Renewal of Credit Period',
  ],

  unitType: [
    'Avoidance - nature',
    'Avoidance - technical',
    'Not Determined',
    'Reduction - nature',
    'Reduction - technical',
    'Removal - nature',
    'Removal - technical',
  ],

  unitStatus: [
    'Buffer',
    'Cancelled',
    'Expired',
    'Held',
    'Inactive',
    'Issued',
    'Rejected',
    'Retired',
  ],

  locationCountry: [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antarctica',
    'Antigua and Barduba',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Cook Islands',
    'Costa Rica',
    'Cote d\'Ivoire',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Democratic People\'s Republic of Korea',
    'Democratic Republic of Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial New Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'European Union',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Holy See',
    'Honduras',
    'Hong Kong S.A.R.',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran (Islamic Republic of)',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Lao People\'s Democratic Republic',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macau S.A.R.',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia (Federated States of)',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands (Kingdom of the)',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Republic of Korea',
    'Republic of Moldova',
    'Romania',
    'Russian Federation',
    'Rwanda',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'St. Kitts and Nevis',
    'St. Lucia',
    'St. Vincent and the Grenadines',
    'State of Palestine',
    'Sudan',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria Arab Republic',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom of Great Britain and Northern Ireland',
    'United Republic of Tanzania',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela (Bolivarian Republic of)',
    'Viet Nam',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ],

  aefT5AuthorizedEntitiesIncorporationCountry: [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antarctica',
    'Antigua and Barduba',
    'Argentina',
    'Armenia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei Darussalam',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Cook Islands',
    'Costa Rica',
    'Cote d\'Ivoire',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Democratic People\'s Republic of Korea',
    'Democratic Republic of Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial New Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'European Union',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Holy See',
    'Honduras',
    'Hong Kong S.A.R.',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran (Islamic Republic of)',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kuwait',
    'Kyrgyzstan',
    'Lao People\'s Democratic Republic',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Macau S.A.R.',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia (Federated States of)',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands (Kingdom of the)',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'Niue',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Qatar',
    'Republic of Korea',
    'Republic of Moldova',
    'Romania',
    'Russian Federation',
    'Rwanda',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'St. Kitts and Nevis',
    'St. Lucia',
    'St. Vincent and the Grenadines',
    'State of Palestine',
    'Sudan',
    'Suriname',
    'Swaziland',
    'Sweden',
    'Switzerland',
    'Syria Arab Republic',
    'Taiwan',
    'Tajikistan',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom of Great Britain and Northern Ireland',
    'United Republic of Tanzania',
    'United States of America',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Venezuela (Bolivarian Republic of)',
    'Viet Nam',
    'Western Sahara',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ],

  locationMapType: [
    'DXF',
    'GML',
    'GPX',
    'GeoJSON',
    'GeoPackage',
    'GeoTIFF',
    'Geodatabases',
    'JGEP 2000',
    'KML / KMZ',
    'LiDAR',
    'Shapefiles',
  ],

  stakeholderType: [
    'Consultant',
    'Developer',
    'Owner',
  ],

  labelType: [
    'Article 6 - Authorisation',
    'Article 6 - Endorsement',
    'Article 6 - Letter of Approvals',
    'Article 6 - Letter of Qualification',
    'Certification',
    'SDG 10 - Reduced inequalities',
  ],

  coBenefitId: [
    'SDG 1 - No poverty',
    'SDG 11 - Sustainable cities and communities',
    'SDG 12 - Responsible consumption and production',
    'SDG 13 - Climate action',
    'SDG 14 - Life below water',
    'SDG 15 - Life on land',
    'SDG 16 - Peace and justice strong institutions',
    'SDG 17 - Partnerships for the goals',
    'SDG 2 - Zero hunger',
    'SDG 3 - Good health and well-being',
    'SDG 4 - Quality education',
    'SDG 5 - Gender equality',
    'SDG 6 - Clean water and sanitation',
    'SDG 7 - Affordable and clean energy',
    'SDG 8 - Decent work and economic growth',
    'SDG 9 - Industry innovation and infrastructure',
  ],

  ratingType: [
    'CCQI',
    'CDP',
  ],

  aefT2AuthorizationsMetric: [
    'GHC',
    'Non-GHG',
  ],

  aefT2AuthorizationsPurposesForAuthorization: [
    'IMP',
    'NDC',
    'NDC and IMP',
    'NDC and OIMP',
    'NDC and OP',
    'OIMP',
    'OP',
  ],

  aefT2AuthorizationsFirstTransferDefinitionOimp: [
    'Authorization',
    'First international transfer',
    'Issuance',
    'Use or cancellation',
  ],

  aefT3ActionsType: [
    'Acquisition',
    'Authorization',
    'Cancellation',
    'First Transfer',
    'Transfer',
    'Use',
  ],

  aefT3ActionsMitigationType: [
    'Emission reductions',
    'Removals',
  ],
};
