export default {
  registries: [
    'American Carbon Registry (ACR)',
    'Article 6.4 Mechanism Registry',
    'Carbon Assets Trading System (CATS)',
    'CDM Registry',
    'Chile National Registry',
    'Climate Action Reserve (CAR)',
    'Costa Rica National Registry',
    'Cultivo',
    'EcoRegistry',
    'Global Carbon Council',
    'Gold Standard',
    'Joint Crediting Mechanism',
    'Mexico National Registry',
    'Open Earth Foundation',
    'Singapore National Registry',
    'Sweden National Registry',
    'Switzerland National Registry',
    'UNFCCC',
    'Verra',
  ],
  projectSector: [
    'Accommodation and food service activities',
    'Activities of extraterritorial organizations and bodies',
    'Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use',
    'Administrative and support service activities',
    'Agriculture; forestry and fishing',
    'Arts, entertainment and recreation',
    'Construction',
    'Education',
    'Electricity; gas, steam and air conditioning supply',
    'Financial and insurance activities',
    'Human health and social work activities',
    'Information and communication',
    'Mining and quarrying',
    'Manufacturing',
    'Other service activities',
    'Professional, scientific and technical activities',
    'Public administration and defence; compulsory social security',
    'Real estate activities',
    'Transportation and storage',
    'Water supply; sewerage, waste management and remediation activities',
    'Wholesale and retail trade; repair of motor vehicles and motorcycles',
    'Not elsewhere classified',
  ],
  projectType: [
    'Afforestation',
    'Avoided Conversion',
    'Coal Mine Methane',
    'Energy Efficiency',
    'Forest Management',
    'Fuel Switching',
    'Geological Storage',
    'Grassland Management',
    'Improved Forest Management',
    'Landfill Gas',
    'Methane Collection and Combustion',
    'N2O Abatement',
    'REDD+',
    'Reforestation',
    'Renewable Energy',
    'Soil Carbon',
    'Waste Management',
    'Wetland Restoration',
    'Not elsewhere classified',
  ],
  projectStatusValues: {
    projectStatus: [
      'Active',
      'Cancelled',
      'Completed',
      'On Hold',
      'Pending',
      'Registered',
      'Under Development',
      'Under Review',
      'Withdrawn',
    ],
  },
  unitMetric: [
    'CO2e',
    'tCO2e',
    'MtCO2e',
    'kgCO2e',
    'gCO2e',
    'Other',
  ],
  validationStatus: [
    'Approved',
    'Pending',
    'Rejected',
    'Under Review',
  ],
  verificationStatus: [
    'Approved',
    'Pending',
    'Rejected',
    'Under Review',
  ],
  methodologyType: [
    'CDM',
    'Gold Standard',
    'VCS',
    'CAR',
    'ACR',
    'Other',
  ],
  locationType: [
    'Country',
    'Region',
    'State/Province',
    'City',
    'Coordinates',
    'Other',
  ],
  issuanceStatus: [
    'Issued',
    'Pending',
    'Cancelled',
    'Retired',
  ],
  unitStatus: [
    'Active',
    'Retired',
    'Cancelled',
    'Transferred',
  ],
  stakeholderType: [
    'Developer',
    'Validator',
    'Verifier',
    'Registry',
    'Government',
    'NGO',
    'Community',
    'Other',
  ],
  labelType: [
    'Certification',
    'Standard',
    'Protocol',
    'Methodology',
    'Other',
  ],
  coBenefitType: [
    'Biodiversity',
    'Community Development',
    'Economic Development',
    'Education',
    'Employment',
    'Health',
    'Water Quality',
    'Air Quality',
    'Other',
  ],
  estimationMethod: [
    'Direct Measurement',
    'Modeling',
    'Default Values',
    'Sampling',
    'Other',
  ],
  ratingScale: [
    '1-5',
    '1-10',
    'A-F',
    'Pass/Fail',
    'Percentage',
    'Other',
  ],
  activityType: [
    'Project Development',
    'Validation',
    'Verification',
    'Registration',
    'Issuance',
    'Retirement',
    'Transfer',
    'Other',
  ],
  aefSubmissionStatus: [
    'Draft',
    'Submitted',
    'Under Review',
    'Approved',
    'Rejected',
    'Withdrawn',
  ],
  aefAuthorizationStatus: [
    'Pending',
    'Approved',
    'Rejected',
    'Expired',
    'Suspended',
  ],
  aefActionType: [
    'Create',
    'Update',
    'Delete',
    'Approve',
    'Reject',
    'Transfer',
  ],
  aefHoldingType: [
    'Issued',
    'Retired',
    'Transferred',
    'Pending',
    'Cancelled',
  ],
  aefEntityType: [
    'Organization',
    'Individual',
    'Government',
    'NGO',
    'Registry',
    'Other',
  ],
};

