# After a release merges to main, auto-update dev dependencies on the develop branch
name: Post-Release Dev Dependency Update

on:
  push:
    branches:
      - main

concurrency:
  group: main-release-check

jobs:
  update-dev-deps:
    name: Auto-update dev dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        uses: Chia-Network/actions/clean-workspace@main

      - name: Checkout develop branch
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.PACKAGE_ADMIN_PAT }}
          fetch-depth: 0
          ref: 'develop'

      - name: Configure commit signing for ChiaAutomation
        uses: Chia-Network/actions/commit-sign/gpg@main
        with:
          gpg_private_key: ${{ secrets.CHIA_AUTOMATION_PRIVATE_GPG_KEY }}
          passphrase: ${{ secrets.CHIA_AUTOMATION_PRIVATE_GPG_PASSPHRASE }}

      - name: Auto-update dev dependencies
        run: |
          echo "Checking if dev dependencies need updating..."
          if $(npx --yes npm-check-updates --dep dev --silent --errorLevel 2)
          then
            echo "No updates found - exiting"
            exit 0
          else
            echo "Applying updates to package.json..."
            npx --yes npm-check-updates --dep dev -u
            echo "Applying updates to the lock file..."
            npm update -D
            echo "Committing updates to the develop branch"
            git add package-lock.json
            git add package.json
            git commit -m "chore: Updating npm dev dependencies"
            git push origin develop
          fi
