name: Delete All Container Packages

on:
  push:
    branches:
      - 'docker-again'

permissions:
  packages: write

jobs:
  delete-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all package versions
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get all package versions and delete them
          gh api -X GET /orgs/Chia-Network/packages/container/cadt/versions --paginate | \
          jq -r '.[].id' | \
          while read -r id; do
            echo "Deleting version $id"
            gh api -X DELETE /orgs/Chia-Network/packages/container/cadt/versions/$id
            sleep 1  # Add small delay to prevent rate limiting
          done
